apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: binding-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin@contoso.com
  
## Bind to AAD Group
#- apiGroup: rbac.authorization.k8s.io
#  kind: Group
#  name: <<AAD_Group_ID>>

## Bind to Service Account
#- kind: ServiceAccount
#  name: my-service-account
#  namespace: default